### PR TITLE
Want to make glot more object oriented

### PR DESCRIPTION
**Pull request by szaydel**
This changeset probably should have come in before my first one, and then that one should have been rebased against master after this changeset was incorporated, if it was going to be. But, they are still largely independent, and so hopefully you could have a look, offer feedback if you want things changed or merge as is.

Thanks, let me know what you would like to see happen.
Regards, Sam.

### CODE REVIEW

**Comment by arafatkatze** [comment]
@szaydel  Wow this is really amazing.    Thanks a lot for this. 

Can you please give me a few days to review your pr?
I will have to make quite a few comments. 

Thanks again

**Comment by szaydel** [comment]
Thanks, no rush at all. I won't have a lot of time to work on this I am sure in next few days. Cheers.

**Comment by arafatkatze** [comment]
@szaydel 
I do have very few changes I would like to see but for now, this looks really great and so I am merging this. I will make the minor changes myself when I am adding new functionalities.
Thanks a lot. 
Regards,
Arafat

**Comment by szaydel** [comment]
It seems to me that perhaps there were not enough tests to reveal issues with the code. I am thinking that this merge was perhaps premature. I suggest reverting it and perhaps before changes are made, tests should be improved. I am not sure if this changeset broke more things than it fixed, but it certainly seems like while tests were passing, they were incomplete and did not reveal issues.

**Comment by szaydel** [comment]
I have been doing some functional testing, beyond the tests that were already there, and I can see that there are a number of issues with this changeset that should be fixed. @Arafatk, please revert this changeset and I am going to work on improving tests, and on improving this changeset as well. Clearly I was too quick to do this PR. My apologies.

**Comment by arafatkatze** [comment]
@szaydel  That's totally cool. Things like these happen from time to time.     
Just take some time and send a new pr with adequate testing and hopefully, it will all work out. 
I am reverting this pr for now.

**Comment by szaydel** [comment]
I think one of the problems with this PR is it breaks with the initial API, which clearly already has consumers. I gave this another thought, and it might be best to rollback and then I can do smaller PRs with a better description of changes. I was not really expecting that you'd merge this thing in without some discussion, and so originally did not give every aspect of the change a good amount of thought. As I look at it now, I probably would do some things differently, and certainly break up PR into pieces.

A number of changes probably should be discussed first, before being merged in, because they likely are not in agreement with initial design of glot.

**Pull request merged**
